---

git_repo: https://github.com/fcrios145/blag_plax
git_ssh_pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCyAmFVJv4rqnWmKjdUSHSTRcGJscT+OccVOS7wETXz9/7Zk20Cjy+4L4qvonCBsDFHKEwclud/rkBHGtOdAf7Q1Ghe9HB1nNiPCR0DTlcQqV8BGKWx3sE1zdrwenRISR+CcHSs+X9ZU1dxb5UtGxZb18Avu5SbNF75R+1CEyzBHspAJ10HNYxqftadRxgGFD4Zztj5vXtvphtfqBqLR3j6AnbmAkK7b6AsL22pKz25+FnuEokBsoARijNPCIDs9aqVcEtZQL0nKbHnWDrMUPR1/3tyXYrr2TOctf0U9yRr9zJ4aFWXvcsonvg6WKOPD21NkFo88s1x+r/HxUS9WZyz fcrios145@gmail.com"
git_ssh_priv_key: "-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAsgJhVSb+K6p1pio3VEh0k0XBibHE/jnHFTku8BE18/f+2ZNt
Ao8vuC+Kr6JwgbAxRyhMHJbnf65ARxrTnQH+0NRoXvRwdZzYjwkdA05XEKlfARil
sd7BNc3a8Hp0SEkfgnB0rPl/WVNXcW+VLRsWW9fAL7uUmzRe+UftQhMswR7KQCdd
BzWMan7WnUcYBhQ+Gc7Y+b17b6YbX6gai0d4+gJ25gJCu2+gLC9tqSs9ufhZ7hKJ
AbKAEYozTwiA7PWqlXBLWUC9Jymx51g6zFD0df97cl2K69kznLX9FPcka/cyeGhV
l73LKJ74Olijjw9tTZBaPPLNcfq/x8VEvVmcswIDAQABAoIBADC0HANbTtGNqvDS
vh6uUE73F/PfkqFoF4NECQaf/t4IbU8EWiAIIytGvrA9RoEFPwZUDTcJRr+VYnrR
6TIdGKX0Z7YLNTXIuyuvd6Ou7H1fieHX54XaB4z8DLodFvGsKBXdRN8KyIAdIGCm
Ae+8aIqqZifpL8ijNJUJy+13J5iSqg0tzIOn4gFvvj+mx+PZQ92OuzCihxFx+YL6
BajquSZzrLIPZhhhzzhDvH1QcJa+d16g8v41zWa+Jb8AsFVxECaL3nj7uUR4m4c1
7ABN9vsabXeLXTg2zRitZXu1FpPRL8dNK+hh6VfG6X6MLMbunAs3jGFAohjeKDrR
O4yrMnkCgYEA4egAw+kv0BsDUj/OObJBFdnvzQY6aylOoxIY54dVeFttbc4EfQOa
V+TuZ8QSYpa1J/CP9oQwge9cUj/mUlKBzuW8LHpkGJjiVjPIMuE/EsBrI2UpEODt
VAj8CUXQz/N4XfRKtl/3+pI3BlJmWc1OBewEiTdyWwQok1FKMU2o9H8CgYEAybj3
BHWMeNVC15DIeBEijjCAMbkJoMlVA9Fp5heSFsKw6pLJN3c3jmfZUZrX+6EkPcDM
xmJ8BCaN7W9h7H/Kte3sGaldBH59fxURWTjk3MS8WqZ/v4jbqiGweF6CvZfdgaGk
IuoxwKFd+cttAhXFEsc/J693+cu+07e4RqYsrc0CgYAGwK+dK5BBUT1lLQEWGmz1
oUEYyNHgOCjgmP7jlNkKMvlvadQahIwNiotR0LuX9NdPbVJwVP06NRR2ZPCWj17P
93ALiFELpy5E02Ftm+wNvHC3ayOyHHcbpvUZtduLC8USUeYV04KPG+XHK5lhn9Bw
PuDX1S925wXreWeVV7PwMwKBgQCFu5JH6oZONVQzBVFiCDoYeh8C1+GCLvelqFfE
qyu22yve16F+nBLA3ig86aL2t0YHiqI3g2MkfUrqdkU9PRtusWUtPhLkv9cDQTxX
IljX47XbgzZ+DIVUrTEJG98hQmUfY8IlQ43oXxKmYC7MixIz+NPtw26OtHy2b75D
WDeWoQKBgBC51q1SzTXvZyeN2Z1q7Kz0F0DlhjSCOonLjlqPErHYVFvQMsEdHe5A
XgFWOdpqBY020MjsFbtHDBYvKI694wiXqpin16iFe5zNqfX9qyYbZlyxVpTv6Da0
iTSpr8d93VjJt8j0vlu6IJdZbo12569q5eaDdETblhTzBfRoJA27
-----END RSA PRIVATE KEY-----"
project_name: blag_plax_project
application_name: blag_plax
git_branch: master
