---

- name: postgresql conf
  template: src=postgresql.j2
            dest=/etc/postgresql/9.1/main/postgresql.conf
            backup=yes

- name: pg_hba.conf
  template: src=pg_hba.j2
            dest=/etc/postgresql/9.1/main/pg_hba.conf
            backup=yes

- name: Restart posgresql
  service: name=postgresql state=restarted 

