- name: Create the SSH public key file
  copy: content="{{ git_ssh_pub_key }}"
        dest=/home/vagrant/.ssh/id_rsa.pub
        mode=0644

- name: Create the SSH private key file
  copy: content="{{ git_ssh_priv_key }}"
        dest=/home/vagrant/.ssh/id_rsa
        mode=0600
